-- Core table for policy transactions
CREATE TABLE POLICY_TRANSACTION (
    policy_no VARCHAR2(50) PRIMARY KEY,
    module_code VARCHAR2(20) NOT NULL,
    product_id VARCHAR2(20) NOT NULL,
    stage_code VARCHAR2(20) NOT NULL,
    amount NUMBER(15,2),
    status VARCHAR2(20) DEFAULT 'PENDING',
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Modules configuration table
CREATE TABLE MODULE_CONFIG (
    module_code VARCHAR2(20) PRIMARY KEY,
    module_name VARCHAR2(100) NOT NULL,
    is_active NUMBER(1) DEFAULT 1
);

-- Products within modules
CREATE TABLE PRODUCT_CONFIG (
    product_id VARCHAR2(20) PRIMARY KEY,
    module_code VARCHAR2(20) REFERENCES MODULE_CONFIG(module_code),
    product_name VARCHAR2(100) NOT NULL
);

-- Schedulers configuration table
CREATE TABLE SCHEDULER_CONFIG (
    id NUMBER PRIMARY KEY,
    scheduler_name VARCHAR2(100) NOT NULL,
    module_code VARCHAR2(20),
    job_class VARCHAR2(255) NOT NULL,
    cron_expression VARCHAR2(50) NOT NULL,
    is_active NUMBER(1) DEFAULT 1
);

-- Scheduler run history
CREATE TABLE SCHEDULER_LOG (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheduler_id NUMBER REFERENCES SCHEDULER_CONFIG(id),
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP,
    status VARCHAR2(20), -- SUCCESS, FAILED, RUNNING
    records_processed NUMBER DEFAULT 0,
    error_message CLOB
);

-- Materialized view for fast dashboard counts
/* Note: Oracle specific syntax */
/*
CREATE MATERIALIZED VIEW MV_STAGE_COUNTS
REFRESH FAST ON DEMAND AS
SELECT module_code, product_id, stage_code, COUNT(*) as cnt, TRUNC(created_date) as txn_date
FROM POLICY_TRANSACTION
GROUP BY module_code, product_id, stage_code, TRUNC(created_date);
*/
